# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a19f3f04242299286a28dd571ed5dd166d7f875f01c38e496932e345c3091dc6eb5a124b2f91df98f44c96bc44684aaed308dd62ed068d142ed47db8872eaf9

test:
  secret_key_base: b39ff29e3cc4e81d1a82ad3896d24b4189fbbba9efa0bcf916d626c398df1495a736d9d37cef3ab2eecda29f945424b56afd2f1a660973dfd682c68c4c6f7537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
